name: testfed

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_ota:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v2
    # Setup Terraform
    - uses: hashicorp/setup-terraform@v1
    # Login to Azure 
    - name: Azure Login 
      uses: azure/login@v1.4.2
      with:
        client-id: ${{ secrets.AZURE_CLIENTID }}
        tenant-id: ${{ secrets.AZURE_TENANTID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}
    # Run az commands
    - name: 'Run az commands'
      run: |
        az account set -s 'alvozza' -o table
        az group list -o table
    - run: terraform init
      working-directory: ./temp
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENTID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_TENANTID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_SUBSCRIPTIONID }}
    - run: terraform plan
      working-directory: ./temp

